apiVersion: v1
kind: Service
metadata:
  name: deploy-react-kubernetes-service
  namespace: harness-delegate-ng
  labels:
    app: deploy-react-kubernetes
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: deploy-react-kubernetes
